export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST"
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export  const CREATE_TRANSACTION_ERROR = "CREATE_TRANSACTION_ERROR"
export const GET_TRANSACTION_REQUEST = "GET_TRANSACTION_REQUEST"
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS"
export  const GET_TRANSACTION_ERROR = "GET_TRANSACTION_ERROR"

