export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export  const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR"
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export  const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR"

